"use client";
import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";



const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ReduxProvider> {children}</ReduxProvider>
            </body>
        </html>
    );
}
